[package]
name = "scrpy-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
